### ISSUE TITLE
EPIC - Legg på forside-design fra Ramsalt

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1522]
Se figma-dokument.

- [x] må ha bruker/tilgang til optimizely (Roger)
- [x] #1643 
- [x] #1697 
- [x] #1606 
- [x] #1607 
- [x] #1605 
- [x] gjennomgang av forsideskisse med ledelsen
- [x] startet utkast på forside

**Comment by arnfinn** [comment]
![image](https://github.com/mong/mongts/assets/136346/46e6bc60-e6bf-4fa7-a704-a066a0ccabfc)

**Comment by larstun** [comment]
Bruke test.skde.no først? https://www.animaapp.com/blog/design-to-code/how-to-export-figma-to-html/

**Comment by larstun** [comment]
Nytt design med ny tekst er utformet og ligger klar til DEV

![Image](https://github.com/mong/mongts/assets/143407861/a084b7bf-0fdc-4c9d-9f82-7afbd9a5368f)

**Comment by larstun** [comment]
Fått tilgang til optimizely, gjennomgang med ledelsen om forside-skisse 6.mai

**Comment by larstun** [comment]
Forside design publisert, godkjent av ledelse. Kun minor tekst og bilde justeringer som må til
