### ISSUE TITLE
EPIC - venstre meny - resultatside

### ISSUE THREAD

**Issue by larstun** [mong/mongts#1609]
Sluttbruker ønsker å kunne filtrere kvalitetsindikatorer på ulike filtre fordi de ønsker å bruke data fra eget sykehus, snevre inn måloppnåelse, osv. 
 
- [x] #1610
- [x] #1611
- [x] #1612
- [x] #1613
- [x] #1774 
- [x] #1775 
- [x] #1777
- [x] #1887
- [x] #1345 

![Image](https://github.com/mong/mongts/assets/143407861/30b96434-b32b-46d4-b15d-30c54c4f59cd)

**Comment by larstun** [comment]
- [ ] klikkbar grensesnitt på filtrering
- [ ] funksjonalitet som endrer på innholdet i resultater
- [ ] søkemotor for innholdet (google søk på ord)
- [ ] årsvisning nedtrekksmeny
