### ISSUE TITLE
EPIC - Dele år inn i kvartal/tertial/halvårlig

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1647]
En del registre vil gjerne vise resultater med finmasket enn per hele år.

Datamodellen må utvides. Må legge inn mulighet for å levere data på kvartal, tertial eller halvår (valgfritt hva man vil levere på, men kun en av de).

- [ ] Må utforske hvordan registeret skal levere inn data for kvartal, tertial, halvårig 
- [ ] Beregning for leverte data over i kvartal, tertial, halvårig
- [ ] Separere visning av graf
- [ ] Lagring av kvartalsvis/halvårig data? Eller kun vise for inneværende år om kvartalsvis/halvårig?
- [ ] Lage ny graf for halvårig/kvartalsvis, gi mulighet til å bytte mellom årlig visning og detaljert visning.
- [ ] Diskusjon om å fjerne "stiplet" linje på graf

Data for desember kan leveres på en av fire måter:

### Kvartal

```csv
ind_id;year;orgnr;var;denominator;context;quarter
hjerteinfarkt_pci_tid;2016;874632562;0;4;caregiver;4
```

### Tertial

```csv
ind_id;year;orgnr;var;denominator;context;third
hjerteinfarkt_pci_tid;2016;874632562;0;4;caregiver;3
```

### Halvårig

```csv
ind_id;year;orgnr;var;denominator;context;half
hjerteinfarkt_pci_tid;2016;874632562;0;4;caregiver;2
```

### Månedlig

```csv
ind_id;year;orgnr;var;denominator;context;month
hjerteinfarkt_pci_tid;2016;874632562;0;4;caregiver;12
```

**Comment by larstun** [comment]
- [ ] Må endre i databasen for å kunne ta inn halvårlig/kvartalsvis
- [ ] Imongr for innlevering av data må endres
- [ ] Ha mulighet i graf for å vise alle år (uten halvårlig/kvartalsvis) [button]
- [ ] Ha mulighet i graf for å vise 3 eller 5 siste år (med halvårlig/kvartalsvis hvis det finnes data) [button]

**Comment by larstun** [comment]
Kan dette gjøres på registerspesifikke sidene? Med et eget valg for det i imongr?

**Comment by Stein-Kato** [comment]
@larstun @arnfinn Skal vi legge denne på is?

**Comment by arnfinn** [comment]
Det hadde gjort sidene våre to-tre ganger bedre syns nå jeg (kunne skrevet milliard ganger bedre, men det ble så voldsomt).

**Comment by Stein-Kato** [comment]
Kunne vi først ha kartlagt om registrene er i stand til å levere fullstendige data kvartal- eller tertialvis? Hvis ikke får vi liten gevinst av å øke tidsoppløsningen.

**Comment by larstun** [comment]
Gjennomføre stegvis med ett register først, for å se om de klarer å levere på denne måten, deretter hvordan fremvisningen av data. Dette kreves omskriving av det meste som har laget tidligere 🫤
