### ISSUE TITLE
EPIC - innholdside - resultatside

### ISSUE THREAD

**Issue by larstun** [mong/mongts#1779]
Innholdsiden skal være visningen av kvalitetsindikatordata i form av enkelvisning og trykke på for å få opp en større visning av data i form av graf. Avhengighet til #1609 , #1616 og #1696 

- [x] Overskrift - Kvalitetsindikator/Målnivå 
- [x] Underskrift - Registernavn / Valgt filter(sykehus) + Nasjonalt
- [x] Indikatornavn med målnivå
- [x] Nedtrekksknapp
- [x] Ekspanderes når trykkes på
- [x] Visning av indikatorinformasjon
- [x] Ønsket målnivå under målnivå
- [x] Valg av grafvisning / skifte mellom grafvisninger
- [ ] Ulike valg for graf (nedlastning, zoom, skjul målnivå)
- [x] Metadata om kvalitetsindikator
- [x] #1778 
- [x] Styling/theme på innholdside

![Image](https://github.com/mong/mongts/assets/143407861/ecc233ef-ad2e-46bd-b159-75de2ba64e4e)

![Image](https://github.com/mong/mongts/assets/143407861/346fadec-5a2e-40e7-8134-cd880765d4f3)
