### ISSUE TITLE
EPIC - Styling/theming av Behandlingskvalitet

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2427]
- [x] Få tak i riktig font-type (Google font - Open jakarta plus) importere rett fonttype (https://github.com/mong/mongts/issues/2431)
- [x] Riktig farge i bakgrunn
- [x] Riktig farge på skrift og komponenter
- [x] Størrelse på skrift (skalering/reaktiv til endring på størrelse av skjerm)
- [x] Ikoner tilsvarende skisse i figma
