### ISSUE TITLE
EPIC - Flytting til Azure

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3260]
- [x] Prøvekjøre apps.skde.no på Azure
- [ ] Planlegge flytting av imongr (Database) - @Stein-Kato @arnfinn (Lager en liste over hva som må flyttes)
(Database, shinyapp (virtuell maskin), identifseringsnøkkel (overgang til Entra-ID), ShinyProxy)

- [ ] Overflytting av brukerkatalog fra gamle autorisasjonsliste (appen imongr)

- [ ] Undersøke med prising ved flytting til Azure (leie virtuell maskin pr mnd?)

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Hvordan ligger vi an med denne?

**Comment by jo-inge-arnes** [comment]
Dette er gammelt. Både nettsider, api-er, databaser og imongr er på Azure nå. Det vi ikke har flyttet, er brukerbasen. Den er fortsatt AWS Cognito og vil ligge der en stund framover.
